name: batlle_bots
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  go_router: ^5.2.0
  google_fonts: ^3.0.1
  web_socket_channel: ^2.2.0
  shelf_plus: ^1.5.0
  rxdart: ^0.27.1
  flame: ^1.5.0
  flame_bloc: ^1.8.1
  tiled: ^0.10.1
  flame_tiled: ^1.9.0
  window_manager: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/